# Generated by Django 3.1.6 on 2021-04-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210429_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='code',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
