# Generated by Django 3.1.6 on 2021-04-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_file_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='prover',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='vc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
