# Generated by Django 3.1.6 on 2021-04-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210430_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesection',
            name='availability_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statusdata',
            name='availability_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='availability_flag',
            field=models.BooleanField(default=True),
        ),
    ]
