# Generated by Django 3.1.6 on 2021-04-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210430_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesection',
            name='code',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='section_category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
