# Generated by Django 3.2 on 2021-05-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_filesection_parent_file_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesection',
            name='parent_file_section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.filesection'),
        ),
    ]
