# Generated by Django 3.2 on 2021-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_filesection_parent_file_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesection',
            name='section_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
